"""empty message

Revision ID: 55b49c4cce11
Revises: ece9f2bc61ca
Create Date: 2020-11-18 16:40:27.614039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b49c4cce11'
down_revision = 'ece9f2bc61ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photos', sa.Column('folder_id', sa.Integer(), nullable=False))
    op.drop_constraint('photos_user_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'photo_folders', ['folder_id'], ['id'])
    op.drop_column('photos', 'user_id')
    op.add_column('sketchbooks', sa.Column('color', sa.String(), nullable=True))
    op.drop_column('sketchbooks', 'cover_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sketchbooks', sa.Column('cover_img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sketchbooks', 'color')
    op.add_column('photos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_user_id_fkey', 'photos', 'users', ['user_id'], ['id'])
    op.drop_column('photos', 'folder_id')
    op.drop_table('photo_folders')
    # ### end Alembic commands ###
